### ISSUE TITLE
Unable to run on Windows 10

### ISSUE THREAD

**Issue by pakoxtror** [near/create-near-app#1053]
After running command 
`npx create-near-app  new-awesome-project`
on my local machine (Windows 10 x64), it fails after 
typing yarn dev and the following appears:

PS C:\Users\username\Desktop\proyectos_dreamcode\new-awesome-project> yarn dev
yarn run v1.22.10
$ nodemon --watch contract -e ts --exec npm run start
[nodemon] 2.0.7
[nodemon] to restart at any time, enter rs
[nodemon] watching path(s): contract\**\*   
[nodemon] watching extensions: ts
[nodemon] starting npm run start
new-awesome-project@0.0.1 prestart C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project
> npm run build:contract:debug && npm run dev:deploy:contract
> new-awesome-project@0.0.1 build:contract:debug C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project
> node contract/compile.js --debug
> greeter@0.0.1 build:debug C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract
> asb --target debug
Whoops, the AssemblyScript compiler has crashed during initialize :-(
Here is a stack trace that may or may not be useful:
AssertionError: assertion failed
at i.assert (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-
project\contract\node_modules\assemblyscript\dist\assemblyscript.js:7:737201)
at E.initialize (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\assemblyscript\dist\assemblyscript.js:7:592660)
at Object.t.initializeProgram (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\assemblyscript\dist\assemblyscript.js:7:435441)        
at C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\assemblyscript\cli\asc.js:817:22
at measure (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\assemblyscript\cli\asc.js:1331:3)
at Object.main (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\assemblyscript\cli\asc.js:815:27)
at compileProject (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\asbuild\dist\commands\build.js:206:9)
at Object.handler (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\asbuild\dist\commands\build.js:107:13)
at Object.runCommand (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\asbuild\node_modules\yargs\build\lib\command.js:196:48)
at Object.parseArgs [as _parseArgs] (C:\Users\wwwda\Desktop\proyectos_dreamcode\new-awesome-project\contract\node_modules\asbuild\node_modules\yargs\build\lib\yargs.js:1071:43)
If it refers to the dist files, try to 'npm install source-map-support' and
run again, which should then show the actual code location in the sources.
If you see where the error is, feel free to send us a pull request. If not,
please let us know: https://github.com/AssemblyScript/assemblyscript/issues
Thank you!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! greeter@0.0.1 build:debug: asb --target debug
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the greeter@0.0.1 build:debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wwwda\AppData\Roaming\npm-cache\_logs\2021-06-14T23_29_56_372Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-awesome-project@0.0.1 build:contract:debug: node contract/compile.js --debug
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-awesome-project@0.0.1 build:contract:debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wwwda\AppData\Roaming\npm-cache\_logs\2021-06-14T23_29_56_409Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-awesome-project@0.0.1 prestart: npm run build:contract:debug && npm run dev:deploy:contract
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-awesome-project@0.0.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wwwda\AppData\Roaming\npm-cache\_logs\2021-06-14T23_29_56_432Z-debug.log
[nodemon] app crashed - waiting for file changes before starting... ` 

And this appears  on the debug.log

[2021-06-14T23_29_56_432Z-debug.log](https://github.com/near/create-near-app/files/6651789/2021-06-14T23_29_56_432Z-debug.log)

**Comment by pakoxtror** [comment]
Running on WSL worked for me!
