### ISSUE TITLE
App doesn't find keypair anymore

### ISSUE THREAD

**Issue by jilt** [near/create-near-app#1395]
Maybe there's been some updates on the near testnet but I was developing on this and the login doesn't seem to work anymore.
Throws an error of "missing keypair" on testnet even when logging in via nera-cli just before the yarn dev command, it fails to compile the contract.
On monday it worked perfectly.

Error log:

` Starting deployment. Account id: dev-1634907132198-2214135, node: https://rpc.testnet.near.org, helper: https://helper.testnet.near.org, file: ./out/main.wasm
An error occured
Error: Can not sign transactions for account dev-1634907132198-2214135 on network testnet, no matching key pair found in InMemorySigner(MergeKeyStore(UnencryptedFileSystemKeyStore(/home/gitpod/.near-credentials), UnencryptedFileSystemKeyStore(/workspace/varda-vault/neardev))).
    at Account.signTransaction (/workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/account.js:74:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/account.js:91:34
    at async Object.exponentialBackoff [as default] (/workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransaction (/workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/account.js:90:24)
    at async devDeploy (/workspace/varda-vault/node_modules/near-cli/commands/dev-deploy.js:50:20)
    at async Object.handler (/workspace/varda-vault/node_modules/near-cli/utils/exit-on-error.js:36:9)
TypedError: Can not sign transactions for account dev-1634907132198-2214135 on network testnet, no matching key pair found in InMemorySigner(MergeKeyStore(UnencryptedFileSystemKeyStore(/home/gitpod/.near-credentials), UnencryptedFileSystemKeyStore(/workspace/varda-vault/neardev))).
    at Account.signTransaction (/workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/account.js:74:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/account.js:91:34
    at async Object.exponentialBackoff [as default] (/workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransaction (/workspace/varda-vault/node_modules/near-cli/node_modules/near-api-js/lib/account.js:90:24)
    at async devDeploy (/workspace/varda-vault/node_modules/near-cli/commands/dev-deploy.js:50:20)
    at async Object.handler (/workspace/varda-vault/node_modules/near-cli/utils/exit-on-error.js:36:9) {
  type: 'KeyNotFound',
  context: undefined
}
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by VuongVu** [comment]
@jilt  @anfinil 
Login with NearCLI or go to `https://wallet.testnet.near.org/` and create an account with an id matching your local id like: `dev-1637315295278-31746576872707`

After login into wallet testnet, you run dev again in your cmd and the app will launch.
Happy coding, sorry for my English is not good to explain.
