### ISSUE TITLE
When running the command `yarn dev` It is showing the error [nodemon] failed to start process, "npm run start" exec not found

### ISSUE THREAD

**Issue by FaizanNehal** [near/create-near-app#1714]
I have installed nodemon using the command `npm install -g nodemon`. But upon running the `yarn dev` it is still throwing this error. The complete error message is below:
```
sh: asb: command not found
[nodemon] failed to start process, "npm run start" exec not found
[nodemon] Error
    at Bus.<anonymous> (/Users/faizannehal/Desktop/first/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:532:35)
    at ChildProcess.<anonymous> (/Users/faizannehal/Desktop/first/node_modules/nodemon/lib/monitor/run.js:190:11)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by hungho66** [comment]
I have the same issue
<img width="979" alt="Screen Shot 2022-05-06 at 10 45 38" src="https://user-images.githubusercontent.com/61680226/167063599-0bf9a23b-d286-4839-a8aa-69fe1a2e9b70.png">

**Comment by gagdiez** [comment]
should be fixed in the latest version
