### ISSUE TITLE
Contract compiled with Rust 1.70.0 not working

### ISSUE THREAD

**Issue by think-in-universe** [near/create-near-app#2009]
### Problem

After creating a new Rust contract with `create-near-app` with latest Rust version 1.70.0, and following the steps to deploy contract, developer failed to view function with `near view <dev-account> get_greeting`.

This issue is reported by developers in community who are learning how to build on NEAR today. 

### How to Reproduce

(1) Install the latest Rust version 1.70.0. For example,

```bash
stable-x86_64-unknown-linux-gnu (default)
rustc 1.70.0 (90c541806 2023-05-31)
```

(2) Create a new project with `create-near-app` command

```bash
npx create-near-app my-project --contract rust --frontend none --tests rust
```

(3) Deploy contract to testnet

```bash
cd ./my-project
npm i
npm run deploy
```

(4) View call function `get_greeting`

```bash
near view <dev-account> get_greeting
```

View call failed and you'll encounter the error as below.

```bash
$ near view dev-1685967486834-62115280035912 get_greeting
View call: dev-1685967486834-62115280035912.get_greeting()
An error occured
Error: Querying [object Object] failed: wasm execution failed with error: CompilationError(PrepareError(Deserialization)).
{
  "block_hash": "5cdGPvRvN8JGKs7AfEPjVJaoVZjhhS35H1WgxrvxmNXR",
  "block_height": 128323323,
  "error": "wasm execution failed with error: CompilationError(PrepareError(Deserialization))",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Account.viewFunction (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Querying [object Object] failed: wasm execution failed with error: CompilationError(PrepareError(Deserialization)).
{
  "block_hash": "5cdGPvRvN8JGKs7AfEPjVJaoVZjhhS35H1WgxrvxmNXR",
  "block_height": 128323323,
  "error": "wasm execution failed with error: CompilationError(PrepareError(Deserialization))",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Account.viewFunction (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'UntypedError',
  context: undefined
}
```

### Notes

This is probably a compatibility issue of Rust SDK 4.0.0 with Rust 1.70.0.

**Comment by frol** [comment]
> `CompilationError(PrepareError`

This usually indicates that the contract defined that it requires host functions that are not going to be provided or has illegal/unsupported operation. We will need to involve nearcore team to help to diagnose it.

**Comment by frol** [comment]
It has been already investigated: https://github.com/near/nearcore/pull/9140#issuecomment-1576655073

Here is where solution is being discussed: https://near.zulipchat.com/#narrow/stream/295306-pagoda.2Fcontract-runtime/topic/sign-ext.20support.20and.20rust.201.2E70.2B

**Comment by jakmeier** [comment]
Unfortunately, without a protocol upgrade, the best workaround is to use rustc <1.69.

**Comment by agostbiro** [comment]
Hey, I've just ran into this. 

I'm wondering if we should add a `rust-toolchain.toml` with the following content to the template to force using Rust 1.69:

```
[toolchain]
channel = "1.69"
```

Happy to provide a PR.

**Comment by frol** [comment]
@agostbiro let’s do what you suggested as a quick temporary fix
