### ISSUE TITLE
src/assets/favicon.ico: Invalid Version: undefined

### ISSUE THREAD

**Issue by secretshardul** [near/create-near-app#804]
I'm unable to use this starter. Here's what I did:

```sh
npx create-near-app near-trial
cd near-trial
npm run dev
```

Same issue is thrown by React starter created with `--frontend=react` flag.

Problem log
```sh
> near-react@0.1.0 start
> echo The app is starting! It will automatically open in your browser when ready && env-cmd -f ./neardev/dev-account.env parcel src/index.html --open

The app is starting! It will automatically open in your browser when ready
Server running at http://localhost:1234 
🚨  /Users/hp/Documents/unblock-hack/near-react/src/assets/favicon.ico: Invalid Version: undefined
    at new SemVer (/Users/hp/Documents/unblock-hack/near-react/node_modules/semver/semver.js:314:11)
    at compare (/Users/hp/Documents/unblock-hack/near-react/node_modules/semver/semver.js:647:10)
    at lt (/Users/hp/Documents/unblock-hack/near-react/node_modules/semver/semver.js:688:10)
    at /Users/hp/Documents/unblock-hack/near-react/node_modules/@babel/preset-env/lib/index.js:280:22
    at Object.default (/Users/hp/Documents/unblock-hack/near-react/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
    at getEnvPlugins (/Users/hp/Documents/unblock-hack/near-react/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/Users/hp/Documents/unblock-hack/near-react/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/Users/hp/Documents/unblock-hack/near-react/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/Users/hp/Documents/unblock-hack/near-react/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/Users/hp/Documents/unblock-hack/near-react/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)
```

![image](https://user-images.githubusercontent.com/49580849/110916220-95d66980-833e-11eb-938e-69a2a25254c1.png)

#### Environment
- Node.js: v15.9.0
- NPM: 7.5.3
- System: MacOS Catalina 10.15.5

**Comment by secretshardul** [comment]
Looks like `env-cmd` is throwing this error. Here's the script from `npm run start` in `package.json`
```sh
env-cmd -f ./neardev/dev-account.env parcel src/index.html --open
```

Running this throws the same error. If I remove `favicon.ico` from `index.html`, it throws error for `index.js`
